/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylwang_ifacerecognition_MyFaceRecognizer */

#ifndef _Included_com_ylwang_ifacerecognition_MyFaceRecognizer
#define _Included_com_ylwang_ifacerecognition_MyFaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylwang_ifacerecognition_MyFaceRecognizer
 * Method:    nativeCreativeModel
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ylwang_ifacerecognition_MyFaceRecognizer_nativeCreativeModel
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceRecognizer
 * Method:    nativeGetSimilarity
 * Signature: (JJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_ylwang_ifacerecognition_MyFaceRecognizer_nativeGetSimilarity
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
