/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ylwang_ifacerecognition_MyFaceDetector */

#ifndef _Included_com_ylwang_ifacerecognition_MyFaceDetector
#define _Included_com_ylwang_ifacerecognition_MyFaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCreateObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeCreateDetectionBasedTrackedObjectObject
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCreateDetectionBasedTrackedObjectObject
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeCreateCascadeClassifierObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCreateCascadeClassifierObject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeDestroyDetectionBasedTrackedObjectObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeDestroyDetectionBasedTrackedObjectObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeDestroyCascadeClassifierObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeDestroyCascadeClassifierObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeSetFaceSize
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeSetFaceSize
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeDetectionBasedTrackedDetect
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeDetectionBasedTrackedDetect
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeCascadeClassfierDetect
 * Signature: (JJJI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCascadeClassfierDetect
  (JNIEnv *, jclass, jlong, jlong, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeEqualizeLeftAndRightHalves
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeEqualizeLeftAndRightHalves
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeGetPreprocessingImage
 * Signature: (JJJII)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeGetPreprocessingImage
  (JNIEnv *, jclass, jlong, jlong, jlong, jint, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeTestDataTrans
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeTestDataTrans
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeGetSimilarity
 * Signature: (JJJ)D
 */
JNIEXPORT jdouble JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeGetSimilarity
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeCreateModel
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCreateModel
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativelearnCollectedFaces
 * Signature: (JLjava/lang/String;Ljava/lang/String;JJI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativelearnCollectedFaces
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeUpdate
 * Signature: (JLjava/lang/String;Ljava/lang/String;JJI)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeUpdate
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong, jlong, jint);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativePredict
 * Signature: (JLjava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativePredict
  (JNIEnv *, jclass, jlong, jstring, jstring, jlong);

/*
 * Class:     com_ylwang_ifacerecognition_MyFaceDetector
 * Method:    nativeFindIrisCenter
 * Signature: (JJDD)V
 */
JNIEXPORT void JNICALL Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeFindIrisCenter
  (JNIEnv *, jclass, jlong, jlong, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
