.TH "iFaceRecognition/docs/search/all_d.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/all_d.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils \fBh\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils h"

.PP
Definition at line 8 of file all_d\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['m_5fblue',['M_BLUE',['\&.\&./i_face_recognition_8cpp\&.html#aba84099b444ae2de2a2588c3d9b971a6',1,'iFaceRecognition\&.cpp']]],
  ['m_5fgreen',['M_GREEN',['\&.\&./i_face_recognition_8cpp\&.html#a80b0a7cdacdac141d4b98dafabbd0caa',1,'iFaceRecognition\&.cpp']]],
  ['m_5fred',['M_RED',['\&.\&./i_face_recognition_8cpp\&.html#a625f3fea32732c3fa32f6b3ddd75f905',1,'iFaceRecognition\&.cpp']]],
  ['mainactivity',['MainActivity',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_main_activity\&.html',1,'com::ylwang::ifacerecognition']]],
  ['mainactivity_2ejava',['MainActivity\&.java',['\&.\&./_main_activity_8java\&.html',1,'']]],
  ['maprotatedimagepoint',['mapRotatedImagePoint',['\&.\&./_image_utils_8h\&.html#a1b0bd411c17d29e527377740bcc96cfa',1,'mapRotatedImagePoint(const CvPoint2D32f pointOrig, const IplImage *image, float angleRadians, float scale DEFAULT(1\&.0f)):&#160
.fi
.PP
Definition at line 1 of file all_d\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
