.TH "com.ylwang.ifacerecognition.MyFaceRecognizer" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ylwang.ifacerecognition.MyFaceRecognizer \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMyFaceRecognizer\fP (String recognizerType)"
.br
.ti -1c
.RI "void \fBload\fP (String filename)"
.br
.ti -1c
.RI "void \fBsave\fP (String filename)"
.br
.ti -1c
.RI "void \fBtrain\fP (List< Mat > src, Mat labels)"
.br
.ti -1c
.RI "void \fBupdate\fP (List< Mat > src, Mat labels)"
.br
.ti -1c
.RI "void \fBpredict\fP (Mat src, int[] label, double[] confidence)"
.br
.ti -1c
.RI "double \fBgetSimilarity\fP (Mat imgA, Mat imgB)"
.br
.ti -1c
.RI "void \fBsetRecognizer\fP (String recognizerType)"
.br
.ti -1c
.RI "void \fBtest\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file MyFaceRecognizer\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.MyFaceRecognizer (StringrecognizerType)\fC [inline]\fP"

.PP
Definition at line 15 of file MyFaceRecognizer\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "double com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.getSimilarity (MatimgA, MatimgB)\fC [inline]\fP"

.PP
Definition at line 73 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.load (Stringfilename)\fC [inline]\fP"

.PP
Definition at line 39 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.predict (Matsrc, int[]label, double[]confidence)\fC [inline]\fP"

.PP
Definition at line 67 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.save (Stringfilename)\fC [inline]\fP"

.PP
Definition at line 46 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.setRecognizer (StringrecognizerType)\fC [inline]\fP"

.PP
Definition at line 79 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.test ()\fC [inline]\fP"

.PP
Definition at line 101 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.train (List< Mat >src, Matlabels)\fC [inline]\fP"

.PP
Definition at line 53 of file MyFaceRecognizer\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.update (List< Mat >src, Matlabels)\fC [inline]\fP"

.PP
Definition at line 60 of file MyFaceRecognizer\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
