.TH "iFaceRecognition Directory Reference" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdocs\fP"
.br
.ti -1c
.RI "directory \fBgen\fP"
.br
.ti -1c
.RI "directory \fBjni\fP"
.br
.ti -1c
.RI "directory \fBobj\fP"
.br
.ti -1c
.RI "directory \fBsrc\fP"
.br
.in -1c
