.TH "iFaceRecognition/docs/search/defines_2.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/defines_2.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['declare_5ftiming',['DECLARE_TIMING',['\&.\&./_image_utils_8h\&.html#a1a466591007005999186254e2db22d11',1,'ImageUtils\&.h']]],
  ['default',['DEFAULT',['\&.\&./_image_utils_8h\&.html#a85d74f656a8218d7b4ada2d0a7b85300',1,'ImageUtils\&.h']]]
]
.fi
.PP
Definition at line 1 of file defines_2\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
