.TH "iFaceRecognition/docs/search/defines_a.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/defines_a.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['use_5fhighgui',['USE_HIGHGUI',['\&.\&./_image_utils__0_87_8cpp\&.html#a53e3d95c499d574b51564a6f5b6c58ad',1,'ImageUtils_0\&.7\&.cpp']]]
]
.fi
.PP
Definition at line 1 of file defines_a\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
