.TH "iFaceRecognition/docs/dynsections.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/dynsections.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "function \fBtoggleVisibility\fP (linkObj)"
.br
.ti -1c
.RI "function \fBupdateStripes\fP ()"
.br
.ti -1c
.RI "function \fBtoggleLevel\fP (level)"
.br
.ti -1c
.RI "function \fBtoggleFolder\fP (id)"
.br
.ti -1c
.RI "function \fBtoggleInherit\fP (id)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "function toggleFolder (id)"

.PP
Definition at line 48 of file dynsections\&.js\&.
.SS "function toggleInherit (id)"

.PP
Definition at line 84 of file dynsections\&.js\&.
.SS "function toggleLevel (level)"

.PP
Definition at line 27 of file dynsections\&.js\&.
.SS "function toggleVisibility (linkObj)"

.PP
Definition at line 1 of file dynsections\&.js\&.
.SS "function updateStripes ()"

.PP
Definition at line 22 of file dynsections\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
