.TH "iFaceRecognition/docs/search/files_8.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/files_8.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['namespaces_5f0_2ejs',['namespaces_0\&.js',['\&.\&./namespaces__0_8js\&.html',1,'']]],
  ['namespaces_5f1_2ejs',['namespaces_1\&.js',['\&.\&./namespaces__1_8js\&.html',1,'']]]
]
.fi
.PP
Definition at line 1 of file files_8\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
