.TH "iFaceRecognition/docs/search/functions_3.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_3.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils_0 \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils_0 cpp"

.PP
Definition at line 4 of file functions_3\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['detect',['detect',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#ae1868fe9bd02b04cf15d03ec5f26edbb',1,'com::ylwang::ifacerecognition::MyFaceDetector']]],
  ['drawcross',['drawCross',['\&.\&./_image_utils_8h\&.html#a359bfe66d2413f7e0f061e6930a529e6',1,'drawCross(IplImage *img, const CvPoint pt, int radius, const CvScalar color):&#160
.fi
.PP
Definition at line 1 of file functions_3\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
