.TH "iFaceRecognition/docs/search/functions_8.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_8.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "iFaceRecognition \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "iFaceRecognition cpp"

.PP
Definition at line 18 of file functions_8\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativecreatemodel',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeCreateModel',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a6ef4114ad942c89c283aa024c1cff8a7',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativecreateobject',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeCreateObject',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a2b05def072131f2b96bef499c32d6f95',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativedestroyobject',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeDestroyObject',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a6376f41ff1ba7ee284fddbb06b24c83e',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativedetect',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeDetect',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a478f26cc59539ff1ec800160d794c2b0',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativeequalizeleftandrighthalves',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeEqualizeLeftAndRightHalves',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#ad7a27e68b3273268252d81be9add52d8',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativefindiriscenter',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeFindIrisCenter',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a8712f2be71d2a0d1a4ec1bd9cfb6a1b3',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativegetpreprocessingimage',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeGetPreprocessingImage',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#afa7c42a9b1f8332c921707913fd0034d',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativegetsimilarity',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeGetSimilarity',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#aca7f4be34c4d78070af2630bef2b56eb',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativelearncollectedfaces',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativelearnCollectedFaces',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a66ad9613b382b80ba1f5606c10a04969',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativepredict',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativePredict',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a7f52d09a8b666ac7d3fded59c23b3eb1',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativesetfacesize',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeSetFaceSize',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#af5f3bcdf934bda4eff9fdec55447c1fa',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativestart',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeStart',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a0a8a04f97614141ea2bae25b737ee7f2',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativestop',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeStop',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a3c8265d7719f032ca3639133afb27631',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativetestdatatrans',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeTestDataTrans',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#ac0754284152443eee178c039382fb955',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fdetectionbasedtracker_5fnativeupdate',['Java_com_ylwang_ifacerecognition_DetectionBasedTracker_nativeUpdate',['\&.\&./com__ylwang__ifacerecognition___detection_based_tracker_8h\&.html#a12fd60ca353e5702a63c7ee53499e64a',1,'com_ylwang_ifacerecognition_DetectionBasedTracker\&.h']]],
  ['java_5fcom_5fylwang_5fifacerecognition_5fmyfacedetector_5fnativecascadeclassfierdetect',['Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCascadeClassfierDetect',['\&.\&./com__ylwang__ifacerecognition___my_face_detector_8h\&.html#ab6c146cb72ed1c97d2b3dc565d315ba4',1,'Java_com_ylwang_ifacerecognition_MyFaceDetector_nativeCascadeClassfierDetect(JNIEnv *, jclass, jlong, jlong, jlong, jint):&#160
.fi
.PP
Definition at line 1 of file functions_8\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
