.TH "iFaceRecognition/docs/search/namespaces_0.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/namespaces_0.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['com',['com',['\&.\&./namespacecom\&.html',1,'']]],
  ['ifacerecognition',['ifacerecognition',['\&.\&./namespacecom_1_1ylwang_1_1ifacerecognition\&.html',1,'com::ylwang']]],
  ['ylwang',['ylwang',['\&.\&./namespacecom_1_1ylwang\&.html',1,'com']]]
]
.fi
.PP
Definition at line 1 of file namespaces_0\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
