.TH "iFaceRecognition/gen/org/opencv/R.java" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/gen/org/opencv/R.java \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBorg\&.opencv\&.R\fP"
.br
.ti -1c
.RI "class \fBorg\&.opencv\&.R\&.attr\fP"
.br
.ti -1c
.RI "class \fBorg\&.opencv\&.R\&.id\fP"
.br
.ti -1c
.RI "class \fBorg\&.opencv\&.R\&.styleable\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBorg\&.opencv\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
