.TH "iFaceRecognition/docs/search/variables_11.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_11.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['type_5fcascadeclassfier',['TYPE_CascadeClassfier',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#a82e0fc22e7bafb98f996cec0036ddecd',1,'com::ylwang::ifacerecognition::MyFaceDetector']]],
  ['type_5fdetectionbasedtracker',['TYPE_DetectionBasedTracker',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#a979e6107b364970f32c49a0a745ed27b',1,'com::ylwang::ifacerecognition::MyFaceDetector']]]
]
.fi
.PP
Definition at line 1 of file variables_11\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
