.TH "iFaceRecognition/docs/search/variables_c.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_c.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['l',['L',['\&.\&./jquery_8js\&.html#a38ee4c0b5f4fe2a18d0c783af540d253',1,'jquery\&.js']]],
  ['labelvector',['labelVector',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#a0863ba8545de50558a1af0454372a06d',1,'com::ylwang::ifacerecognition::AddPersonActivity']]]
]
.fi
.PP
Definition at line 1 of file variables_c\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
