.TH "iFaceRecognition/docs/search/variables_13.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_13.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['v',['V',['\&.\&./jquery_8js\&.html#a8b88915d3d3a06e98248a89807b077fa',1,'jquery\&.js']]]
]
.fi
.PP
Definition at line 1 of file variables_13\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
