.TH "iFaceRecognition/docs/search/variables_a.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_a.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "all_0 \fBjs\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "all_0 js"

.PP
Definition at line 5 of file variables_a\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['java_5fdetector',['JAVA_DETECTOR',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#a92e0385a3c8ee550a81af5f5ef8761dc',1,'com\&.ylwang\&.ifacerecognition\&.AddPersonActivity\&.JAVA_DETECTOR()'],['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_face_rec_activity\&.html#af54f5b0dc73fa48f7155fddc26352cd9',1,'com\&.ylwang\&.ifacerecognition\&.FaceRecActivity\&.JAVA_DETECTOR()']]],
  ['jquery',['jQuery',['\&.\&./jquery_8js\&.html#aa676d9980e4aff2d9210b4c8e0e1dad9',1,'jquery\&.js']]],
  ['js',['js',['\&.\&./all__0_8js\&.html#a975aa2394af6b74243e6c1b73de2583a',1,'js():&#160
.fi
.PP
Definition at line 1 of file variables_a\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
