.TH "iFaceRecognition/docs/search/all_4.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/all_4.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils_0 \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils_0 cpp"

.PP
Definition at line 19 of file all_4\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['debug',['DEBUG',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_build_config\&.html#ad15f3da74675b7a5c794fe3cb5aaf155',1,'com::ylwang::ifacerecognition::BuildConfig']]],
  ['declare_5ftiming',['DECLARE_TIMING',['\&.\&./_image_utils_8h\&.html#a1a466591007005999186254e2db22d11',1,'ImageUtils\&.h']]],
  ['default',['DEFAULT',['\&.\&./_image_utils_8h\&.html#a85d74f656a8218d7b4ada2d0a7b85300',1,'ImageUtils\&.h']]],
  ['defines_5f0_2ejs',['defines_0\&.js',['\&.\&./defines__0_8js\&.html',1,'']]],
  ['defines_5f1_2ejs',['defines_1\&.js',['\&.\&./defines__1_8js\&.html',1,'']]],
  ['defines_5f2_2ejs',['defines_2\&.js',['\&.\&./defines__2_8js\&.html',1,'']]],
  ['defines_5f3_2ejs',['defines_3\&.js',['\&.\&./defines__3_8js\&.html',1,'']]],
  ['defines_5f4_2ejs',['defines_4\&.js',['\&.\&./defines__4_8js\&.html',1,'']]],
  ['defines_5f5_2ejs',['defines_5\&.js',['\&.\&./defines__5_8js\&.html',1,'']]],
  ['defines_5f6_2ejs',['defines_6\&.js',['\&.\&./defines__6_8js\&.html',1,'']]],
  ['defines_5f7_2ejs',['defines_7\&.js',['\&.\&./defines__7_8js\&.html',1,'']]],
  ['defines_5f8_2ejs',['defines_8\&.js',['\&.\&./defines__8_8js\&.html',1,'']]],
  ['defines_5f9_2ejs',['defines_9\&.js',['\&.\&./defines__9_8js\&.html',1,'']]],
  ['defines_5fa_2ejs',['defines_a\&.js',['\&.\&./defines__a_8js\&.html',1,'']]],
  ['detect',['detect',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#ae1868fe9bd02b04cf15d03ec5f26edbb',1,'com::ylwang::ifacerecognition::MyFaceDetector']]],
  ['diglogtag',['DiglogTAG',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#a3b06d9001082a4677004249062b8e3b2',1,'com::ylwang::ifacerecognition::AddPersonActivity']]],
  ['drawcross',['drawCross',['\&.\&./_image_utils_8h\&.html#a359bfe66d2413f7e0f061e6930a529e6',1,'drawCross(IplImage *img, const CvPoint pt, int radius, const CvScalar color):&#160
.fi
.PP
Definition at line 1 of file all_4\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
