.TH "iFaceRecognition/docs/search/all_12.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/all_12.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils_0 \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils_0 cpp"

.PP
Definition at line 4 of file all_12\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['save',['save',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_recognizer\&.html#ad86265a556a48cac61e5ece56066bd5b',1,'com::ylwang::ifacerecognition::MyFaceRecognizer']]],
  ['savefloatimage',['saveFloatImage',['\&.\&./_image_utils_8h\&.html#abe19b08095b1fa9012ae8bab9c1a4972',1,'saveFloatImage(const char *filename, const IplImage *srcImg):&#160
.fi
.PP
Definition at line 1 of file all_12\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
