.TH "iFaceRecognition/docs/search/all_5.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/all_5.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBif\fP (bD!==L)"
.br
.ti -1c
.RI "jquery \fBif\fP (!\fBbw\fP()&amp;&amp;bv[e]===\fBbw\fP)"
.br
.ti -1c
.RI "\fBif\fP (!bv\&.length)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "jquery \fBjs\fP =function(\fBbw\fP, by, bx){return this\&.animate(bv, \fBbw\fP, by, bx)}}):&#160"
.br
.ti -1c
.RI "jquery jquery \fBbw\fP =b\&.cssProps[bz]||bz"
.br
.ti -1c
.RI "\fBelse\fP {\fBif\fP(bE &amp;&amp;&quot;get&quot;in bE &amp;&amp;(bB=bE\&.get(bx, \fBfalse\fP, by))!==L){return bB}return bv[\fBbw\fP]}}, css:function(by, bx, bv){var \fBbw\fP, e;bx=b\&.camelCase(bx);e=b\&.cssHooks[bx];bx=b\&.cssProps[bx]||bx;\fBif\fP(bx===&quot;cssFloat&quot;){bx=&quot;float&quot;}\fBif\fP(e &amp;&amp;&quot;get&quot;in e &amp;&amp;(\fBbw\fP=e\&.get(by, \fBtrue\fP, bv))!==L){return \fBbw\fP}else{\fBif\fP(Z){return Z(by, bx)}}}, swap:function(bx, \fBbw\fP, by){var e={};for(var bv in \fBbw\fP){e[bv]=bx\&.style[bv];bx\&.style[bv]=\fBbw\fP[bv]}by\&.call(bx);for(bv in \fBbw\fP){bx\&.style[bv]=e[bv]}}}):&#160"
.br
.ti -1c
.RI "interval \fB__pad0__\fP"
.br
.ti -1c
.RI "interval \fBstop\fP"
.br
.ti -1c
.RI "\fBa3\fP =null}, speeds:{slow:600, fast:200, _default:400}, step:{opacity:function(e){b\&.style(e\&.elem,&quot;opacity&quot;, e\&.now)}, _default:function(e){\fBif\fP(e\&.elem\&.style &amp;&amp;e\&.elem\&.style[e\&.prop]!=null){e\&.elem\&.style[e\&.prop]=e\&.now+e\&.unit}\fBelse\fP{e\&.elem[e\&.prop]=e\&.now}}}}):&#160"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "if (bD! = \fC=L\fP)"

.PP
Definition at line 7 of file all_5\&.js\&.
.SS "if (!bv\&.length)"

.PP
Definition at line 7 of file all_5\&.js\&.
.SS "jquery if (!\fBbw\fP()&amp;&amp;bv[e] = \fC==\fBbw\fP\fP)"

.PP
Definition at line 7 of file all_5\&.js\&.
.SH "Variable Documentation"
.PP 
.SS "interval __pad0__"

.PP
Definition at line 7 of file all_5\&.js\&.
.SS "a3 =null}, speeds:{slow:600, fast:200, _default:400}, step:{opacity:function(e){b\&.style(e\&.elem,&quot;opacity&quot;, e\&.now)}, _default:function(e){\fBif\fP(e\&.elem\&.style &amp;&amp;e\&.elem\&.style[e\&.prop]!=null){e\&.elem\&.style[e\&.prop]=e\&.now+e\&.unit}\fBelse\fP{e\&.elem[e\&.prop]=e\&.now}}}}):&#160"

.PP
Definition at line 7 of file all_5\&.js\&.
.SS "jquery jquery bw =b\&.cssProps[bz]||bz"

.PP
Definition at line 7 of file all_5\&.js\&.
.SS "else {\fBif\fP(bE &amp;&amp;&quot;get&quot;in bE &amp;&amp;(bB=bE\&.get(bx, \fBfalse\fP, by))!==L){return bB}return bv[\fBbw\fP]}}, css:function(by, bx, bv){var \fBbw\fP, e;bx=b\&.camelCase(bx);e=b\&.cssHooks[bx];bx=b\&.cssProps[bx]||bx;\fBif\fP(bx===&quot;cssFloat&quot;){bx=&quot;float&quot;}\fBif\fP(e &amp;&amp;&quot;get&quot;in e &amp;&amp;(\fBbw\fP=e\&.get(by, \fBtrue\fP, bv))!==L){return \fBbw\fP}else{\fBif\fP(Z){return Z(by, bx)}}}, swap:function(bx, \fBbw\fP, by){var e={};for(var bv in \fBbw\fP){e[bv]=bx\&.style[bv];bx\&.style[bv]=\fBbw\fP[bv]}by\&.call(bx);for(bv in \fBbw\fP){bx\&.style[bv]=e[bv]}}}):&#160"

.PP
Definition at line 7 of file all_5\&.js\&.
.SS "jquery js =function(\fBbw\fP, by, bx){return this\&.animate(bv, \fBbw\fP, by, bx)}}):&#160"

.PP
Definition at line 3 of file all_5\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['each',['each',['\&.\&./jquery_8js\&.html#a871ff39db627c54c710a3e9909b8234c',1,'each([&quot;height&quot;,&quot;width&quot;], function(bv, e){b\&.cssHooks[e]={get:function(by, bx, bw){var bz;if(bx){if(by\&.offsetWidth!==0){return p(by, e, bw)}else{b\&.swap(by, a7, function(){bz=p(by, e, bw)})}return bz}}, set:function(bw, bx){if(bc\&.test(bx)){bx=parseFloat(bx);if(bx &gt;=0){return bx+&quot;px&quot;}}else{return bx}}}}):&#160
.fi
.PP
Definition at line 1 of file all_5\&.js\&.
.SS "interval stop"

.PP
Definition at line 7 of file all_5\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
