.TH "com.ylwang.ifacerecognition.MainActivity" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ylwang.ifacerecognition.MainActivity \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Activity\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "boolean \fBonCreateOptionsMenu\fP (Menu menu)"
.br
.ti -1c
.RI "boolean \fBonMenuItemSelected\fP (int featureId, MenuItem item)"
.br
.ti -1c
.RI "boolean \fBonOptionsItemSelected\fP (MenuItem item)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCreate\fP (Bundle savedInstanceState)"
.br
.ti -1c
.RI "void \fBonResume\fP ()"
.br
.ti -1c
.RI "void \fBonDestroy\fP ()"
.br
.ti -1c
.RI "void \fBonPause\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file MainActivity\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onCreate (BundlesavedInstanceState)\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 13 of file MainActivity\&.java\&.
.SS "boolean com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onCreateOptionsMenu (Menumenu)\fC [inline]\fP"

.PP
Definition at line 22 of file MainActivity\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onDestroy ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 64 of file MainActivity\&.java\&.
.SS "boolean com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onMenuItemSelected (intfeatureId, MenuItemitem)\fC [inline]\fP"

.PP
Definition at line 39 of file MainActivity\&.java\&.
.SS "boolean com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onOptionsItemSelected (MenuItemitem)\fC [inline]\fP"

.PP
Definition at line 45 of file MainActivity\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onPause ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 71 of file MainActivity\&.java\&.
.SS "void com\&.ylwang\&.ifacerecognition\&.MainActivity\&.onResume ()\fC [inline]\fP, \fC [protected]\fP"

.PP
Definition at line 31 of file MainActivity\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
