.TH "iFaceRecognition/jni/com_ylwang_ifacerecognition_MyFaceRecognizer.h" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/jni/com_ylwang_ifacerecognition_MyFaceRecognizer.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <jni\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "JNIEXPORT jlong JNICALL \fBJava_com_ylwang_ifacerecognition_MyFaceRecognizer_nativeCreativeModel\fP (JNIEnv *, jobject, jstring)"
.br
.ti -1c
.RI "JNIEXPORT jdouble JNICALL \fBJava_com_ylwang_ifacerecognition_MyFaceRecognizer_nativeGetSimilarity\fP (JNIEnv *, jobject, jlong, jlong)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "JNIEXPORT jlong JNICALL Java_com_ylwang_ifacerecognition_MyFaceRecognizer_nativeCreativeModel (JNIEnv *, jobject, jstring)"

.PP
Definition at line 834 of file iFaceRecognition\&.cpp\&.
.SS "JNIEXPORT jdouble JNICALL Java_com_ylwang_ifacerecognition_MyFaceRecognizer_nativeGetSimilarity (JNIEnv *, jobject, jlong, jlong)"

.PP
Definition at line 854 of file iFaceRecognition\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
