.TH "iFaceRecognition/docs/search/defines_7.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/defines_7.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['m_5fblue',['M_BLUE',['\&.\&./i_face_recognition_8cpp\&.html#aba84099b444ae2de2a2588c3d9b971a6',1,'iFaceRecognition\&.cpp']]],
  ['m_5fgreen',['M_GREEN',['\&.\&./i_face_recognition_8cpp\&.html#a80b0a7cdacdac141d4b98dafabbd0caa',1,'iFaceRecognition\&.cpp']]],
  ['m_5fred',['M_RED',['\&.\&./i_face_recognition_8cpp\&.html#a625f3fea32732c3fa32f6b3ddd75f905',1,'iFaceRecognition\&.cpp']]]
]
.fi
.PP
Definition at line 1 of file defines_7\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
