.TH "iFaceRecognition/docs/search/functions_a.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_a.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils \fBh\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils h"

.PP
Definition at line 3 of file functions_a\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['maprotatedimagepoint',['mapRotatedImagePoint',['\&.\&./_image_utils_8h\&.html#a1b0bd411c17d29e527377740bcc96cfa',1,'mapRotatedImagePoint(const CvPoint2D32f pointOrig, const IplImage *image, float angleRadians, float scale DEFAULT(1\&.0f)):&#160
.fi
.PP
Definition at line 1 of file functions_a\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
