.TH "iFaceRecognition/docs/search/functions_9.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_9.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "recognition \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "recognition cpp"

.PP
Definition at line 3 of file functions_9\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['learncollectedfaces',['learnCollectedFaces',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#a8b3ab47b385b728751b8671de8fd1948',1,'com\&.ylwang\&.ifacerecognition\&.MyFaceDetector\&.learnCollectedFaces()'],['\&.\&./recognition_8cpp\&.html#a77011dad5a5a0c4572b88a8b136da84a',1,'learnCollectedFaces(const vector&lt; Mat &gt; preprocessedFaces, const vector&lt; int &gt; faceLabels, const string facerecAlgorithm):&#160
.fi
.PP
Definition at line 1 of file functions_9\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
