.TH "iFaceRecognition/docs/search/functions_11.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_11.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['vector_5frect_5fto_5fmat',['vector_Rect_to_Mat',['\&.\&./i_face_recognition_8cpp\&.html#ae61e8997a85eb90d229bc61aabb25e1c',1,'iFaceRecognition\&.cpp']]]
]
.fi
.PP
Definition at line 1 of file functions_11\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
