.TH "iFaceRecognition/docs/search/functions_10.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_10.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['update',['update',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_recognizer\&.html#a9620187ff75104c8732885bea5218085',1,'com::ylwang::ifacerecognition::MyFaceRecognizer']]],
  ['updatefacerecognizer',['updateFaceRecognizer',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#a01e301978a1f5e6ab85aa15426eb874e',1,'com::ylwang::ifacerecognition::MyFaceDetector']]],
  ['updatestripes',['updateStripes',['\&.\&./dynsections_8js\&.html#a8f7493ad859d4fbf2523917511ee7177',1,'dynsections\&.js']]]
]
.fi
.PP
Definition at line 1 of file functions_10\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
