.TH "iFaceRecognition/docs/search/functions_c.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_c.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils_0 \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils_0 cpp"

.PP
Definition at line 6 of file functions_c\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['p',['p',['\&.\&./jquery_8js\&.html#a2335e57f79b6acfb6de59c235dc8a83e',1,'jquery\&.js']]],
  ['predict',['predict',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_detector\&.html#affd29f3578749bb0b9facef259da0347',1,'com\&.ylwang\&.ifacerecognition\&.MyFaceDetector\&.predict()'],['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_my_face_recognizer\&.html#a4e6deb61a398723d78794c2f4e7a1d1d',1,'com\&.ylwang\&.ifacerecognition\&.MyFaceRecognizer\&.predict()']]],
  ['printarray2d',['printArray2D',['\&.\&./_image_utils__0_87_8cpp\&.html#aa22edb30325622da19c52e7d2993cc8b',1,'ImageUtils_0\&.7\&.cpp']]],
  ['printdatarange',['printDataRange',['\&.\&./_image_utils_8h\&.html#aa61845612ab6c1b95f56d909b02c2b49',1,'printDataRange(const CvArr *src, const char *msg):&#160
.fi
.PP
Definition at line 1 of file functions_c\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
