.TH "iFaceRecognition/docs/search/functions_2.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/functions_2.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "ImageUtils_0 \fBcpp\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "ImageUtils_0 cpp"

.PP
Definition at line 3 of file functions_2\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['combineimages',['combineImages',['\&.\&./_image_utils_8h\&.html#ae69519b4e45351bf4eb791a53d4a6690',1,'combineImages(int nArgs,\&.\&.\&.):&#160
.fi
.PP
Definition at line 1 of file functions_2\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
