.TH "org.opencv.R" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
org.opencv.R \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBattr\fP"
.br
.ti -1c
.RI "class \fBid\fP"
.br
.ti -1c
.RI "class \fBstyleable\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file R\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
