.TH "iFaceRecognition/docs/search/variables_4.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_4.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['debug',['DEBUG',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_build_config\&.html#ad15f3da74675b7a5c794fe3cb5aaf155',1,'com::ylwang::ifacerecognition::BuildConfig']]],
  ['diglogtag',['DiglogTAG',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#a3b06d9001082a4677004249062b8e3b2',1,'com::ylwang::ifacerecognition::AddPersonActivity']]]
]
.fi
.PP
Definition at line 1 of file variables_4\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
