.TH "iFaceRecognition/docs/search/variables_1.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_1.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.ti -1c
.RI "all_4 \fBjs\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "all_4 js"

.PP
Definition at line 4 of file variables_1\&.js\&.
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['a',['a',['\&.\&./jquery_8js\&.html#aa4d4888597588a84fd5b1184d00c91f3',1,'jquery\&.js']]],
  ['a3',['a3',['\&.\&./all__4_8js\&.html#a509a674bd7926c5406b815a055d17834',1,'a3():&#160
.fi
.PP
Definition at line 1 of file variables_1\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
