.TH "iFaceRecognition/docs/search/variables_d.js" 3 "Sat Jun 14 2014" "Version 1.3" "iFaceRecognition@YuliWANG" \" -*- nroff -*-
.ad l
.nh
.SH NAME
iFaceRecognition/docs/search/variables_d.js \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBsearchData\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "var searchData"
\fBInitial value:\fP
.PP
.nf
=
[
  ['mlabel',['mLabel',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#a9830e6f5b75f0364eb3f32c279fec949',1,'com\&.ylwang\&.ifacerecognition\&.AddPersonActivity\&.mLabel()'],['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_face_rec_activity\&.html#a4e07098d21aa4b683f967615dcdfd34e',1,'com\&.ylwang\&.ifacerecognition\&.FaceRecActivity\&.mLabel()']]],
  ['mlabelmap',['mLabelMap',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#a82a12cfa830ba5674cbbc1494b73960c',1,'com\&.ylwang\&.ifacerecognition\&.AddPersonActivity\&.mLabelMap()'],['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_face_rec_activity\&.html#a0c9c6ca50d284092d2dc4de4adf2a035',1,'com\&.ylwang\&.ifacerecognition\&.FaceRecActivity\&.mLabelMap()']]],
  ['mopencvcameraview',['mOpenCvCameraView',['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_add_person_activity\&.html#af31b09aaa22a4f6b09064e053de6afff',1,'com\&.ylwang\&.ifacerecognition\&.AddPersonActivity\&.mOpenCvCameraView()'],['\&.\&./classcom_1_1ylwang_1_1ifacerecognition_1_1_face_rec_activity\&.html#ad1fd8e310de27a3f5b1f0e03e62e48fb',1,'com\&.ylwang\&.ifacerecognition\&.FaceRecActivity\&.mOpenCvCameraView()']]]
]
.fi
.PP
Definition at line 1 of file variables_d\&.js\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for iFaceRecognition@YuliWANG from the source code\&.
